# Generated by Django 5.2 on 2025-04-11 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafting_time', models.IntegerField(default=0)),
                ('process_energy', models.IntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crafting.machine')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItemLinkInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crafting.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crafting.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='inputs',
            field=models.ManyToManyField(related_name='recipe_inputs', through='Crafting.RecipeItemLinkInput', to='Crafting.item'),
        ),
        migrations.CreateModel(
            name='RecipeItemLinkOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crafting.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crafting.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='outputs',
            field=models.ManyToManyField(related_name='recipe_outputs', through='Crafting.RecipeItemLinkOutput', to='Crafting.item'),
        ),
    ]
