# Generated by Django 5.2 on 2025-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crafting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
