# Generated by Django 5.2 on 2025-04-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crafting', '0002_alter_item_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
