# Generated by Django 5.2 on 2025-05-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crafting', '0003_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitemlinkinput',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_inputs', to='Crafting.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeitemlinkoutput',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_outputs', to='Crafting.recipe'),
        ),
    ]
