# Generated by Django 5.2 on 2025-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crafting', '0004_alter_recipeitemlinkinput_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitemlinkinput',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
